# Generated by Django 5.1.7 on 2025-03-13 15:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securitylog',
            name='details',
        ),
        migrations.AddField(
            model_name='securitylog',
            name='ip_address',
            field=models.GenericIPAddressField(default='0.0.0.0'),
        ),
        migrations.AddField(
            model_name='securitylog',
            name='user_agent',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='mfa_method',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('app', 'Google Authenticator')], default='email', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='totp_secret',
            field=models.CharField(blank=True, help_text='TOTP secret for Google Authenticator.', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='securitylog',
            name='event_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='securitylog',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
