# Generated by Django 5.1.7 on 2025-04-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "auth_system",
            "0002_remove_securitylog_details_securitylog_ip_address_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="securitylog",
            name="status",
            field=models.CharField(
                choices=[("success", "Success"), ("failure", "Failure")],
                default="success",
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
